### ISSUE TITLE
I want to add hdmi to output video based on your project

### ISSUE THREAD

**Issue by Ajfil** [sefaburakokcu/finn-quantized-yolo#4]
hi， @sefaburakokcu ，I want to add hdmi to output video based on your project,but i only have .bit and .hwh,You can provide tcl scripts or porject itself?thank you!

**Comment by bestamigunay** [comment]
Hi @Ajfil, we cannot provide tcl script or project right now, however you can go to [our medium post](https://medium.com/@bestamigunay1/end-to-end-deployment-of-lpyolo-low-precision-yolo-for-face-detection-on-fpga-13c3284ed14b) for bitstream synthesis. When the synthesis is finished, you can find the Vivado project under the `/tmp` folder. You will be able to add HDMI IP to the block design. Soon, we will add the jupyter notebook files to the repo, also.
