### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'list' and 'int'

### ISSUE THREAD

**Issue by josphat552** [sefaburakokcu/finn-quantized-yolo#5]
I am trying to run one of your onnx output in finn but i get the error below : 
![Capture](https://user-images.githubusercontent.com/79630710/230879407-42bdbffe-ce58-47f2-a007-b2b6c5479bf0.PNG)

**Comment by sefaburakokcu** [comment]
Hi Josphat,

Can you provide the full error log and your code?

**Comment by josphat552** [comment]
The problem was caused by using the onnx model directly in which some files might have deprecated. regenerating the onnx using  brevitas solved the problem. or maybe the platform i am using is not directly compatible with the onnx module provided
